name: Python Package using Conda

on: 
  pull_request:
    branches: [prod]

jobs:
  build-linux:
    runs-on: self-hosted
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
